# Generated by Django 6.0 on 2025-12-26 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_type', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('EMERGENCY', 'Emergency'), ('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('subjective', models.TextField(blank=True, help_text="Patient's complaints and symptoms")),
                ('objective', models.TextField(blank=True, help_text='Physical examination findings and vital signs')),
                ('assessment', models.TextField(blank=True, help_text='Diagnosis and clinical impression')),
                ('plan', models.TextField(blank=True, help_text='Treatment plan and recommendations')),
                ('outcome', models.TextField(blank=True, help_text='Follow-up results and patient outcome')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('encounter_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-encounter_date'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(help_text='ICD-10 or ICD-11 code', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('diagnosis_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('DIFFERENTIAL', 'Differential')], default='PRIMARY', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('diagnosed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='ehr.encounter')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-diagnosed_date'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(blank=True, help_text='LOINC or local lab code', max_length=50)),
                ('test_category', models.CharField(choices=[('HEMATOLOGY', 'Hematology'), ('CHEMISTRY', 'Chemistry'), ('MICROBIOLOGY', 'Microbiology'), ('RADIOLOGY', 'Radiology'), ('PATHOLOGY', 'Pathology'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('result_value', models.CharField(help_text='Test result value', max_length=200)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=50)),
                ('reference_range', models.CharField(blank=True, help_text='Normal reference range', max_length=200)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('CRITICAL', 'Critical'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('interpretation', models.TextField(blank=True, help_text='Clinical interpretation of results')),
                ('performing_lab', models.CharField(blank=True, max_length=200)),
                ('specimen_type', models.CharField(blank=True, help_text='e.g., Blood, Urine', max_length=100)),
                ('collection_date', models.DateTimeField()),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='ehr.encounter')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., twice daily, every 8 hours', max_length=100)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation')], default='ORAL', max_length=20)),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity', models.PositiveIntegerField(help_text='Total quantity prescribed')),
                ('refills', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for taking the medication')),
                ('indication', models.CharField(blank=True, help_text='Reason for prescription', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('prescribed_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='ehr.encounter')),
            ],
            options={
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies')),
                ('medical_history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='ehr_patient_last_na_2c9c00_idx'), models.Index(fields=['date_of_birth'], name='ehr_patient_date_of_678d99_idx')],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='ehr.patient'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', '-encounter_date'], name='ehr_encount_patient_fb0d03_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='ehr_encount_status_d3c784_idx'),
        ),
    ]
